### ISSUE TITLE
[Bug] Error in english.txt file 

### ISSUE THREAD

**Issue by johnnyde94** [Chinilla/chinilla-blockchain#60]
### What happened?

Hello there is an error in C:\Users\USERNAME\AppData\Local\chinilla-blockchain\app-1.1.0\resources\app.asar.unpacked\daemon\chinilla\util\english.txt the word "exchange" is misspelled. I had this same issue with another fork a while back.  I Just had to fix the spelling and it worked. Just a heads up.

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by edwardteach42** [comment]
Thank you for reporting this.  This has been fixed in 2b4016a5f61cb60fbabf5bde3745bfdecc3781b3 amd will be added to the next release shortly.
